services:
  - type: web
    name: kmka-2-0
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18
